import { Resource } from "./AfricaExamPrepDataStructure";

const resources: Resource[] = [
  {
    id: "resource-001",
    type: "document",
    title: "Limits Notes",
    subjectId: "subject-001",
    series: "Bac_D",
    topicId: "topic-001",
    url: "https://example.com/resources/limits.pdf",
    description: "Detailed notes on limits for Bac D Math.",
    level: "Terminale",
    examId: "exam-001",
    thumbnail: "https://example.com/thumbs/limits.png",
    offlineAvailable: true,
    premiumOnly: false,
    metadata: {
      fileSize: 2,
      format: "PDF",
      language: "French",
      tags: ["limits", "calculus"],
      difficulty: "intermediate",
      prerequisites: [],
      lastUpdated: "2025-01-01T00:00:00Z",
      version: "1.0",
      contributors: ["admin-001"],
      license: "CC BY 4.0",
    },
    accessibility: {
      hasTranscript: false,
      hasSubtitles: false,
      hasAudioDescription: false,
    },
    analytics: {
      views: 500,
      downloads: 100,
      averageRating: 4.5,
      userFeedback: [],
    },
  },
  {
    id: "resource-002",
    type: "document",
    title: "Dissertation Guide",
    subjectId: "subject-002",
    series: "Bac_D",
    topicId: "topic-002",
    url: "https://example.com/resources/dissertation.pdf",
    description: "Guide to writing dissertations for Bac D French.",
    level: "Terminale",
    examId: "exam-001",
    thumbnail: "https://example.com/thumbs/dissertation.png",
    offlineAvailable: true,
    premiumOnly: false,
    metadata: {
      fileSize: 1.5,
      format: "PDF",
      language: "French",
      tags: ["dissertation", "literature"],
      difficulty: "advanced",
      prerequisites: [],
      lastUpdated: "2025-01-01T00:00:00Z",
      version: "1.0",
      contributors: ["admin-001"],
      license: "CC BY 4.0",
    },
    accessibility: {
      hasTranscript: false,
      hasSubtitles: false,
      hasAudioDescription: false,
    },
    analytics: {
      views: 400,
      downloads: 80,
      averageRating: 4.0,
      userFeedback: [],
    },
  },
];

export { resources };