import { User } from "./AfricaExamPrepDataStructure";

const user: User = {
  id: "user-001",
  name: "Adoum Ouang-namou Emmanuel",
  email: "adoum.emmanuel@example.com",
  avatar: "https://example.com/avatars/adoum.png",
  country: "Chad",
  timeZone: "Africa/Ndjamena",
  preferredLanguage: "French",
  schoolName: "Lycée de Ndjamena",
  gradeLevel: "Terminale",
  parentEmail: "parent@example.com",
  createdAt: "2025-01-01T00:00:00Z",
  lastLogin: "2025-06-02T12:00:00Z",
  isPremium: false,
  subscription: {
    type: "free",
    startDate: "2025-01-01T00:00:00Z",
    expiresAt: null,
    paymentStatus: "active",
    features: ["basicContent"],
    accessLevel: "basic",
  },
  preferences: {
    notifications: {
      general: true,
      dailyReminderTime: "18:00",
      challengeNotifications: false,
      progressUpdates: true,
    },
    darkMode: false,
    fontSize: "medium",
    preferredContentFormat: "text",
    enableHints: true,
    autoPlayAudio: false,
    showStepSolutions: true,
    leaderboardVisibility: true,
    allowFriendRequests: true,
    multilingualSupport: ["French"],
  },
  settings: {
    learningStyle: "visual",
    motivation: "Pass Bac D with distinction",
    preferredStudySessionLength: 45,
  },
  progress: {
    selectedExam: "exam-001",
    selectedSeries: "Bac_D",
    selectedLevel: "Terminale",
    xp: 1500,
    level: 3,
    streak: { current: 5, longest: 7, lastStudyDate: "2025-06-01T00:00:00Z" },
    goalDate: "2025-07-15T00:00:00Z",
    totalQuizzes: 10,
    averageScore: 75,
    completedTopics: ["topic-001"],
    weakSubjects: ["subject-002"],
    badges: ["badge-001"],
    achievements: ["achievement-001"],
    progressSummary: { completedPercentage: 20, remainingTopics: 8 },
  },
  analyticsId: "analytics-001",
  notes: ["note-001"],
  hintsUsed: ["hint-001"],
  bookmarks: ["bookmark-001"],
  friends: ["user-002"],
  tutorId: "user-002",
  socialProfile: {
    userId: "user-001",
    bio: "Terminale student aiming for Bac D excellence",
    publicAchievements: ["achievement-001"],
    visibility: "public",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com/in/adoum" },
    ],
  },
  onboardingStatusId: "onboarding-001",
  _indexes: {
    email: "adoum.emmanuel@example.com",
    selectedExam: "exam-001",
    selectedSeries: "Bac_D",
    level: 3,
    totalXp: 1500,
  },
};

export { user };
