const mongoose = require("mongoose");
const { Subject } = require("./models/learning/subject.model");

// Connect to MongoDB
const MONGO_URI = "mongodb://localhost:27017/AfricaExamPrep";
mongoose
  .connect(MONGO_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => console.log("Connecté à MongoDB"))
  .catch((err) => console.error("Erreur de connexion:", err));

// Liste complète des matières pour tous les systèmes éducatifs africains
const subjects = [
  // === LANGUES ===
  {
    name: "Français",
    slug: "francais",
    icon: "📘",
    color: "#0000FF",
    description:
      "Étude de la langue et littérature française, grammaire, analyse de textes et expression.",
    longDescription:
      "Matière fondamentale dans les pays francophones couvrant la maîtrise de la langue française à travers l'étude de la grammaire, de l'orthographe, de la conjugaison, l'analyse littéraire et l'expression écrite et orale. Inclut l'étude des œuvres classiques et contemporaines de la littérature francophone africaine et mondiale.",
    examIds: [],
    series: ["A", "C", "D", "E", "F", "G", "TI", "L", "ES", "S"],
    category: "langues",
    subcategory: "langue française",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 150,
    tags: [
      "grammaire",
      "littérature",
      "expression écrite",
      "analyse de texte",
      "francophonie",
    ],
    keywords: [
      "français",
      "langue",
      "littérature",
      "grammaire",
      "orthographe",
      "francophone",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Anglais",
    slug: "anglais",
    icon: "🇬🇧",
    color: "#FF1744",
    description:
      "Langue anglaise : compréhension, expression orale et écrite, littérature anglophone.",
    longDescription:
      "Matière essentielle dans tous les systèmes africains. Couvre les quatre compétences linguistiques, la littérature anglophone (britannique, américaine, africaine), la civilisation anglo-saxonne et la communication internationale.",
    examIds: [],
    series: [
      "A",
      "C",
      "D",
      "E",
      "F",
      "G",
      "TI",
      "L",
      "ES",
      "S",
      "Arts",
      "Science",
      "Commercial",
    ],
    category: "langues",
    subcategory: "langue anglaise",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 140,
    tags: [
      "anglais",
      "langue étrangère",
      "communication",
      "littérature anglophone",
      "civilisation",
    ],
    keywords: [
      "anglais",
      "english",
      "langue",
      "communication",
      "vocabulaire",
      "anglophone",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Arabe",
    slug: "arabe",
    icon: "📜",
    color: "#8B008B",
    description:
      "Langue et littérature arabes, grammaire, textes classiques et modernes.",
    longDescription:
      "Matière importante dans les pays arabophones et musulmans d'Afrique. Étude de la langue arabe classique et moderne, grammaire, littérature arabe classique et contemporaine, civilisation arabo-musulmane et textes religieux.",
    examIds: [],
    series: ["A", "C", "D", "L", "Adab", "Ulum"],
    category: "langues",
    subcategory: "langue arabe",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 130,
    tags: [
      "arabe",
      "langue",
      "littérature",
      "grammaire",
      "civilisation",
      "islam",
    ],
    keywords: [
      "arabe",
      "langue",
      "littérature",
      "grammaire",
      "culture",
      "musulman",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Portugais",
    slug: "portugais",
    icon: "🇵🇹",
    color: "#228B22",
    description: "Langue portugaise pour les pays lusophones d'Afrique.",
    longDescription:
      "Matière principale dans les pays lusophones (Angola, Mozambique, Cap-Vert, Guinée-Bissau, São Tomé-et-Príncipe). Couvre la grammaire, la littérature lusophone africaine et brésilienne, l'expression écrite et orale.",
    examIds: [],
    series: ["A", "C", "D", "Humanidades", "Ciencias"],
    category: "langues",
    subcategory: "langue portugaise",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 140,
    tags: ["portugais", "lusophone", "littérature", "grammaire", "expression"],
    keywords: [
      "portugais",
      "lusophone",
      "langue",
      "littérature",
      "angola",
      "mozambique",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Kiswahili",
    slug: "kiswahili",
    icon: "🌍",
    color: "#FF9800",
    description: "Langue swahilie, importante en Afrique de l'Est.",
    longDescription:
      "Langue officielle au Kenya, Tanzanie, Ouganda et parlée dans plusieurs pays d'Afrique de l'Est. Étude de la grammaire, de la littérature swahilie, de la culture bantoue et de l'histoire de l'Afrique de l'Est.",
    examIds: [],
    series: ["Arts", "Science", "Commercial", "Technical"],
    category: "langues",
    subcategory: "langues africaines",
    isActive: true,
    difficulty: "facile",
    estimatedHours: 120,
    tags: ["kiswahili", "swahili", "afrique de l'est", "bantou", "culture"],
    keywords: [
      "kiswahili",
      "swahili",
      "kenya",
      "tanzanie",
      "ouganda",
      "bantou",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Afrikaans",
    slug: "afrikaans",
    icon: "🇿🇦",
    color: "#4CAF50",
    description: "Langue afrikaans, principalement en Afrique du Sud.",
    longDescription:
      "Une des langues officielles d'Afrique du Sud. Étude de la grammaire, de la littérature afrikaans, de l'histoire et de la culture afrikaner dans le contexte sud-africain.",
    examIds: [],
    series: ["Arts", "Science", "Commercial"],
    category: "langues",
    subcategory: "langues officielles",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 120,
    tags: ["afrikaans", "afrique du sud", "littérature", "culture"],
    keywords: [
      "afrikaans",
      "afrique du sud",
      "langue",
      "culture",
      "littérature",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Langues Nationales",
    slug: "langues-nationales",
    icon: "🗣️",
    color: "#795548",
    description:
      "Étude des langues locales africaines (Wolof, Hausa, Yoruba, Amharique, etc.).",
    longDescription:
      "Matière couvrant les principales langues africaines selon les pays : Wolof (Sénégal), Hausa (Nigeria, Niger), Yoruba (Nigeria), Amharique (Éthiopie), Bambara (Mali), Lingala (RDC), etc. Préservation du patrimoine linguistique africain.",
    examIds: [],
    series: ["A", "L", "Arts"],
    category: "langues",
    subcategory: "langues africaines",
    isActive: true,
    difficulty: "facile",
    estimatedHours: 100,
    tags: [
      "langues africaines",
      "patrimoine",
      "culture",
      "tradition",
      "identité",
    ],
    keywords: [
      "wolof",
      "hausa",
      "yoruba",
      "amharique",
      "bambara",
      "lingala",
      "africain",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },

  // === MATHÉMATIQUES ===
  {
    name: "Mathématiques",
    slug: "mathematiques",
    icon: "➗",
    color: "#FF0000",
    description: "Algèbre, géométrie, analyse, probabilités et statistiques.",
    longDescription:
      "Discipline fondamentale couvrant l'algèbre, la géométrie euclidienne et analytique, l'analyse mathématique, les probabilités, les statistiques et la logique mathématique. Essentielle pour les séries scientifiques et économiques.",
    examIds: [],
    series: ["C", "D", "E", "TI", "S", "ES", "Science", "Technical"],
    category: "mathematiques",
    subcategory: "mathématiques générales",
    isActive: true,
    difficulty: "difficile",
    estimatedHours: 200,
    tags: [
      "algèbre",
      "géométrie",
      "analyse",
      "probabilités",
      "statistiques",
      "logique",
    ],
    keywords: [
      "mathématiques",
      "calcul",
      "équations",
      "fonctions",
      "géométrie",
      "statistiques",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Mathématiques Appliquées",
    slug: "mathematiques-appliquees",
    icon: "📊",
    color: "#E91E63",
    description:
      "Mathématiques orientées vers les applications pratiques et techniques.",
    longDescription:
      "Mathématiques appliquées aux domaines techniques, économiques et scientifiques. Inclut la recherche opérationnelle, les mathématiques financières, la modélisation et les statistiques appliquées.",
    examIds: [],
    series: ["E", "F", "G", "TI", "Technical", "Commercial"],
    category: "mathematiques",
    subcategory: "mathématiques appliquées",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 160,
    tags: [
      "mathématiques appliquées",
      "modélisation",
      "statistiques",
      "finance",
      "technique",
    ],
    keywords: [
      "mathématiques",
      "appliquées",
      "modélisation",
      "statistiques",
      "finance",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },

  // === SCIENCES ===
  {
    name: "Physique-Chimie",
    slug: "physique-chimie",
    icon: "⚗️",
    color: "#008000",
    description:
      "Lois physiques et chimiques, mécanique, électricité, réactions chimiques.",
    longDescription:
      "Science expérimentale combinant physique et chimie. Couvre la mécanique, l'électricité, l'optique, la thermodynamique, la chimie organique et inorganique, les réactions chimiques et la structure de la matière.",
    examIds: [],
    series: ["C", "D", "TI", "S", "Science"],
    category: "sciences",
    subcategory: "sciences physiques",
    isActive: true,
    difficulty: "difficile",
    estimatedHours: 180,
    tags: [
      "physique",
      "chimie",
      "mécanique",
      "électricité",
      "réactions",
      "expériences",
    ],
    keywords: [
      "physique",
      "chimie",
      "expériences",
      "formules",
      "laboratoire",
      "matière",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Sciences de la Vie et de la Terre",
    slug: "sciences-de-la-vie-et-de-la-terre",
    icon: "🌱",
    color: "#00FF00",
    description:
      "Biologie, géologie, écosystèmes, génétique et sciences de la Terre.",
    longDescription:
      "Discipline intégrant biologie et géologie. Étude des êtres vivants, de leur fonctionnement, évolution, écosystèmes, génétique, ainsi que la structure et l'évolution de la Terre, géologie africaine.",
    examIds: [],
    series: ["C", "D", "S", "Science"],
    category: "sciences",
    subcategory: "sciences naturelles",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 160,
    tags: [
      "biologie",
      "géologie",
      "écosystèmes",
      "génétique",
      "évolution",
      "environnement",
    ],
    keywords: [
      "biologie",
      "géologie",
      "nature",
      "environnement",
      "cellules",
      "évolution",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Biologie",
    slug: "biologie",
    icon: "🧬",
    color: "#4CAF50",
    description:
      "Étude du vivant : cellules, génétique, physiologie, écologie.",
    longDescription:
      "Science du vivant couvrant la biologie cellulaire, la génétique, la physiologie humaine et animale, l'écologie, la botanique, la zoologie et la microbiologie. Accent sur la biodiversité africaine.",
    examIds: [],
    series: ["C", "D", "S", "Science", "Agriculture"],
    category: "sciences",
    subcategory: "biologie",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 140,
    tags: [
      "biologie",
      "cellules",
      "génétique",
      "physiologie",
      "écologie",
      "biodiversité",
    ],
    keywords: [
      "biologie",
      "vivant",
      "cellules",
      "génétique",
      "écologie",
      "biodiversité",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Chimie",
    slug: "chimie",
    icon: "🧪",
    color: "#FF5722",
    description: "Chimie générale, organique, inorganique et analytique.",
    longDescription:
      "Étude de la matière et de ses transformations. Couvre la chimie générale, organique, inorganique, analytique, la biochimie et les applications industrielles. Importance des ressources minérales africaines.",
    examIds: [],
    series: ["C", "D", "S", "Science", "Technical"],
    category: "sciences",
    subcategory: "chimie",
    isActive: true,
    difficulty: "difficile",
    estimatedHours: 140,
    tags: [
      "chimie",
      "réactions",
      "molécules",
      "laboratoire",
      "analyse",
      "industrie",
    ],
    keywords: [
      "chimie",
      "réactions",
      "molécules",
      "laboratoire",
      "analyse",
      "matière",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Physique",
    slug: "physique",
    icon: "⚛️",
    color: "#2196F3",
    description:
      "Mécanique, électricité, optique, thermodynamique, physique moderne.",
    longDescription:
      "Science de la matière et de l'énergie. Couvre la mécanique classique, l'électromagnétisme, l'optique, la thermodynamique, la physique moderne (relativité, quantique) et l'astrophysique.",
    examIds: [],
    series: ["C", "D", "S", "Science", "Technical"],
    category: "sciences",
    subcategory: "physique",
    isActive: true,
    difficulty: "difficile",
    estimatedHours: 160,
    tags: [
      "physique",
      "mécanique",
      "électricité",
      "optique",
      "énergie",
      "forces",
    ],
    keywords: [
      "physique",
      "mécanique",
      "électricité",
      "optique",
      "énergie",
      "forces",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Sciences Générales",
    slug: "sciences-generales",
    icon: "🔬",
    color: "#20B2AA",
    description: "Cours intégré de sciences pour les examens généraux.",
    longDescription:
      "Cours multidisciplinaire couvrant les bases de la biologie, physique et chimie. Approche intégrée des sciences naturelles adaptée aux examens généraux et à l'initiation scientifique.",
    examIds: [],
    series: ["General", "Arts", "Commercial"],
    category: "sciences",
    subcategory: "sciences générales",
    isActive: true,
    difficulty: "facile",
    estimatedHours: 120,
    tags: [
      "sciences",
      "général",
      "biologie",
      "physique",
      "chimie",
      "initiation",
    ],
    keywords: ["sciences", "général", "biologie", "physique", "chimie", "base"],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },

  // === SCIENCES SOCIALES ===
  {
    name: "Histoire-Géographie",
    slug: "histoire-geographie",
    icon: "🌍",
    color: "#FFA500",
    description:
      "Histoire africaine et mondiale, géographie physique et humaine.",
    longDescription:
      "Matière combinant histoire et géographie. Analyse des événements historiques majeurs, civilisations africaines, géographie physique et humaine, avec accent sur l'Afrique et ses relations avec le monde.",
    examIds: [],
    series: ["A", "C", "D", "E", "L", "ES", "Arts", "Commercial"],
    category: "sciences-sociales",
    subcategory: "histoire et géographie",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 140,
    tags: [
      "histoire",
      "géographie",
      "afrique",
      "civilisations",
      "monde",
      "cartes",
    ],
    keywords: [
      "histoire",
      "géographie",
      "afrique",
      "cartes",
      "chronologie",
      "civilisations",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Histoire",
    slug: "histoire",
    icon: "📚",
    color: "#8D6E63",
    description:
      "Histoire de l'Afrique et du monde, civilisations, événements majeurs.",
    longDescription:
      "Étude chronologique et thématique de l'histoire africaine précoloniale, coloniale et postcoloniale, ainsi que l'histoire mondiale. Accent sur les civilisations africaines, la traite, la colonisation et les indépendances.",
    examIds: [],
    series: ["A", "L", "ES", "Arts"],
    category: "sciences-sociales",
    subcategory: "histoire",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 120,
    tags: [
      "histoire",
      "afrique",
      "civilisations",
      "colonisation",
      "indépendance",
      "chronologie",
    ],
    keywords: [
      "histoire",
      "afrique",
      "civilisations",
      "colonisation",
      "indépendance",
      "passé",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Géographie",
    slug: "geographie",
    icon: "🗺️",
    color: "#4CAF50",
    description: "Géographie physique, humaine, économique et régionale.",
    longDescription:
      "Étude de l'espace terrestre, géographie physique (climat, relief, hydrographie), géographie humaine (population, urbanisation), géographie économique et régionale avec focus sur l'Afrique.",
    examIds: [],
    series: ["A", "L", "ES", "Arts", "Commercial"],
    category: "sciences-sociales",
    subcategory: "géographie",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 120,
    tags: [
      "géographie",
      "cartes",
      "climat",
      "population",
      "économie",
      "régions",
    ],
    keywords: [
      "géographie",
      "cartes",
      "climat",
      "population",
      "économie",
      "espace",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Éducation Civique et Morale",
    slug: "education-civique-et-morale",
    icon: "⚖️",
    color: "#A52A2A",
    description: "Citoyenneté, institutions, droits et devoirs, éthique.",
    longDescription:
      "Formation à la citoyenneté et aux valeurs morales. Étude des institutions démocratiques africaines, droits et devoirs du citoyen, éthique, valeurs sociales et développement durable.",
    examIds: [],
    series: [
      "A",
      "C",
      "D",
      "E",
      "L",
      "ES",
      "S",
      "Arts",
      "Science",
      "Commercial",
    ],
    category: "sciences-sociales",
    subcategory: "éducation civique",
    isActive: true,
    difficulty: "facile",
    estimatedHours: 80,
    tags: [
      "citoyenneté",
      "institutions",
      "éthique",
      "droits",
      "devoirs",
      "démocratie",
    ],
    keywords: [
      "civique",
      "citoyenneté",
      "institutions",
      "démocratie",
      "valeurs",
      "éthique",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Sociologie",
    slug: "sociologie",
    icon: "👥",
    color: "#9C27B0",
    description: "Étude des sociétés, groupes sociaux et phénomènes sociaux.",
    longDescription:
      "Analyse des structures sociales, institutions, groupes sociaux, changements sociaux, sociologie urbaine et rurale, avec focus sur les sociétés africaines contemporaines.",
    examIds: [],
    series: ["A", "L", "ES", "Arts"],
    category: "sciences-sociales",
    subcategory: "sociologie",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 100,
    tags: [
      "sociologie",
      "société",
      "groupes sociaux",
      "institutions",
      "changement",
    ],
    keywords: [
      "sociologie",
      "société",
      "social",
      "groupes",
      "institutions",
      "changement",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },

  // === ÉCONOMIE ===
  {
    name: "Économie",
    slug: "economie",
    icon: "💰",
    color: "#FFD700",
    description:
      "Principes économiques, microéconomie, macroéconomie, développement.",
    longDescription:
      "Étude des mécanismes économiques, microéconomie et macroéconomie, systèmes économiques, développement économique africain, économie internationale et politiques économiques.",
    examIds: [],
    series: ["E", "ES", "Commercial"],
    category: "sciences-sociales",
    subcategory: "économie",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 150,
    tags: [
      "économie",
      "développement",
      "marchés",
      "finance",
      "commerce",
      "afrique",
    ],
    keywords: [
      "économie",
      "finance",
      "développement",
      "marchés",
      "commerce",
      "afrique",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Sciences Économiques et Sociales",
    slug: "sciences-economiques-et-sociales",
    icon: "📊",
    color: "#4682B4",
    description: "Économie, sociologie, science politique intégrées.",
    longDescription:
      "Discipline interdisciplinaire combinant économie, sociologie et science politique. Analyse des phénomènes sociaux contemporains, inégalités, institutions et politiques publiques en Afrique.",
    examIds: [],
    series: ["E", "ES"],
    category: "sciences-sociales",
    subcategory: "sciences économiques et sociales",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 160,
    tags: [
      "économie",
      "sociologie",
      "politique",
      "société",
      "statistiques",
      "développement",
    ],
    keywords: [
      "économie",
      "sociologie",
      "société",
      "politique",
      "statistiques",
      "social",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Comptabilité",
    slug: "comptabilite",
    icon: "📋",
    color: "#607D8B",
    description:
      "Principes comptables, gestion financière, analyse des comptes.",
    longDescription:
      "Formation aux techniques comptables, tenue des livres, analyse financière, comptabilité générale et analytique, gestion budgétaire et contrôle de gestion pour les entreprises africaines.",
    examIds: [],
    series: ["G", "Commercial", "Technical"],
    category: "sciences-sociales",
    subcategory: "comptabilité",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 140,
    tags: [
      "comptabilité",
      "finance",
      "gestion",
      "entreprise",
      "budget",
      "analyse",
    ],
    keywords: [
      "comptabilité",
      "finance",
      "gestion",
      "entreprise",
      "budget",
      "comptes",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Commerce",
    slug: "commerce",
    icon: "🛒",
    color: "#228B22",
    description: "Techniques commerciales, marketing, gestion d'entreprise.",
    longDescription:
      "Formation aux techniques commerciales, marketing, gestion d'entreprise, relations clients, commerce international, e-commerce et entrepreneuriat adapté au contexte africain.",
    examIds: [],
    series: ["G", "Commercial"],
    category: "sciences-sociales",
    subcategory: "commerce",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 140,
    tags: [
      "commerce",
      "marketing",
      "entreprise",
      "vente",
      "gestion",
      "entrepreneuriat",
    ],
    keywords: [
      "commerce",
      "marketing",
      "entreprise",
      "vente",
      "gestion",
      "business",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },

  // === LITTÉRATURE ET PHILOSOPHIE ===
  {
    name: "Philosophie",
    slug: "philosophie",
    icon: "🤔",
    color: "#800080",
    description:
      "Réflexion philosophique, logique, éthique, philosophie africaine.",
    longDescription:
      "Réflexion critique sur les grandes questions existentielles, épistémologiques, éthiques et politiques. Inclut la philosophie occidentale, la philosophie africaine traditionnelle et contemporaine, la logique et l'argumentation.",
    examIds: [],
    series: ["A", "C", "D", "L", "Arts"],
    category: "litterature",
    subcategory: "philosophie",
    isActive: true,
    difficulty: "difficile",
    estimatedHours: 120,
    tags: [
      "philosophie",
      "réflexion",
      "éthique",
      "logique",
      "afrique",
      "pensée",
    ],
    keywords: [
      "philosophie",
      "réflexion",
      "éthique",
      "logique",
      "pensée",
      "sagesse",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Littérature",
    slug: "litterature",
    icon: "📖",
    color: "#9C27B0",
    description:
      "Littérature africaine et mondiale, analyse d'œuvres, genres littéraires.",
    longDescription:
      "Étude approfondie de la littérature africaine (orale et écrite), littérature mondiale, analyse d'œuvres, genres littéraires, histoire littéraire et critique littéraire. Valorisation du patrimoine littéraire africain.",
    examIds: [],
    series: ["A", "L", "Arts"],
    category: "litterature",
    subcategory: "littérature",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 130,
    tags: [
      "littérature",
      "œuvres",
      "analyse",
      "critique",
      "afrique",
      "patrimoine",
    ],
    keywords: [
      "littérature",
      "œuvres",
      "analyse",
      "critique",
      "auteurs",
      "textes",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },

  // === ARTS ===
  {
    name: "Arts Plastiques",
    slug: "arts-plastiques",
    icon: "🎨",
    color: "#E91E63",
    description:
      "Dessin, peinture, sculpture, arts visuels, art africain traditionnel.",
    longDescription:
      "Formation artistique couvrant le dessin, la peinture, la sculpture, les arts visuels contemporains et l'art africain traditionnel. Développement de la créativité et de l'expression artistique.",
    examIds: [],
    series: ["A", "L", "Arts"],
    category: "arts",
    subcategory: "arts plastiques",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 120,
    tags: [
      "arts",
      "dessin",
      "peinture",
      "sculpture",
      "créativité",
      "tradition",
    ],
    keywords: [
      "arts",
      "dessin",
      "peinture",
      "sculpture",
      "créativité",
      "artistique",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Musique",
    slug: "musique",
    icon: "🎵",
    color: "#FF9800",
    description:
      "Théorie musicale, pratique instrumentale, musique africaine traditionnelle.",
    longDescription:
      "Formation musicale incluant la théorie musicale, la pratique instrumentale, le chant, l'histoire de la musique, avec un accent particulier sur les musiques traditionnelles africaines et contemporaines.",
    examIds: [],
    series: ["A", "L", "Arts"],
    category: "arts",
    subcategory: "musique",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 100,
    tags: ["musique", "instruments", "chant", "tradition", "rythme", "mélodie"],
    keywords: [
      "musique",
      "instruments",
      "chant",
      "rythme",
      "mélodie",
      "africaine",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Éducation Physique et Sportive",
    slug: "education-physique-et-sportive",
    icon: "🏃",
    color: "#FF4500",
    description: "Activités physiques, sports, santé, développement corporel.",
    longDescription:
      "Formation physique et sportive visant le développement des capacités motrices, de l'endurance, de l'esprit d'équipe et du fair-play. Inclut diverses disciplines sportives et l'éducation à la santé.",
    examIds: [],
    series: [
      "A",
      "C",
      "D",
      "E",
      "L",
      "ES",
      "S",
      "Arts",
      "Science",
      "Commercial",
    ],
    category: "arts",
    subcategory: "éducation physique",
    isActive: true,
    difficulty: "facile",
    estimatedHours: 100,
    tags: [
      "sport",
      "santé",
      "activité physique",
      "endurance",
      "équipe",
      "fair-play",
    ],
    keywords: ["sport", "physique", "activité", "exercice", "santé", "équipe"],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },

  // === TECHNOLOGIE ===
  {
    name: "Technologie",
    slug: "technologie",
    icon: "🔧",
    color: "#808080",
    description:
      "Technologies industrielles, mécanique, électrotechnique, automatisation.",
    longDescription:
      "Formation technique couvrant les technologies industrielles, la mécanique, l'électrotechnique, l'automatisation, les nouvelles technologies et l'innovation technologique adaptée au développement africain.",
    examIds: [],
    series: ["F", "G", "TI", "Technical"],
    category: "technologie",
    subcategory: "technologie industrielle",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 180,
    tags: [
      "technologie",
      "industrie",
      "mécanique",
      "électrotechnique",
      "innovation",
      "développement",
    ],
    keywords: [
      "technologie",
      "industrie",
      "mécanique",
      "électricité",
      "innovation",
      "technique",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Informatique",
    slug: "informatique",
    icon: "💻",
    color: "#00CED1",
    description:
      "Programmation, bureautique, réseaux, technologies numériques.",
    longDescription:
      "Formation aux technologies de l'information et de la communication. Couvre la programmation, les bases de données, les réseaux, la bureautique, le web et les technologies numériques pour le développement africain.",
    examIds: [],
    series: ["F", "TI", "Technical", "Science"],
    category: "technologie",
    subcategory: "informatique",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 140,
    tags: [
      "informatique",
      "programmation",
      "numérique",
      "réseaux",
      "web",
      "développement",
    ],
    keywords: [
      "informatique",
      "programmation",
      "ordinateur",
      "numérique",
      "web",
      "logiciels",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Électronique",
    slug: "electronique",
    icon: "🔌",
    color: "#FF5722",
    description: "Circuits électroniques, composants, systèmes électroniques.",
    longDescription:
      "Étude des circuits électroniques, composants électroniques, systèmes numériques et analogiques, télécommunications et applications électroniques dans l'industrie et les services.",
    examIds: [],
    series: ["F", "TI", "Technical"],
    category: "technologie",
    subcategory: "électronique",
    isActive: true,
    difficulty: "difficile",
    estimatedHours: 160,
    tags: [
      "électronique",
      "circuits",
      "composants",
      "systèmes",
      "télécommunications",
      "numérique",
    ],
    keywords: [
      "électronique",
      "circuits",
      "composants",
      "systèmes",
      "télécommunications",
      "digital",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },

  // === MATIÈRES SPÉCIALISÉES ===
  {
    name: "Agriculture",
    slug: "agriculture",
    icon: "🌾",
    color: "#8BC34A",
    description: "Sciences agricoles, agronomie, élevage, développement rural.",
    longDescription:
      "Formation aux sciences agricoles, agronomie, techniques d'élevage, gestion des ressources naturelles, développement rural durable et sécurité alimentaire en Afrique.",
    examIds: [],
    series: ["Agriculture", "Technical"],
    category: "sciences",
    subcategory: "agriculture",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 160,
    tags: [
      "agriculture",
      "agronomie",
      "élevage",
      "rural",
      "sécurité alimentaire",
      "durable",
    ],
    keywords: [
      "agriculture",
      "agronomie",
      "élevage",
      "rural",
      "alimentaire",
      "cultures",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Sciences Islamiques",
    slug: "sciences-islamiques",
    icon: "☪️",
    color: "#4CAF50",
    description: "Études islamiques, Coran, Hadith, jurisprudence islamique.",
    longDescription:
      "Étude approfondie de l'Islam : Coran, Hadith, jurisprudence islamique (Fiqh), histoire islamique, civilisation islamique et son impact en Afrique, éthique islamique.",
    examIds: [],
    series: ["Adab", "Ulum", "Islamic"],
    category: "sciences-sociales",
    subcategory: "études religieuses",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 140,
    tags: [
      "islam",
      "coran",
      "hadith",
      "jurisprudence",
      "civilisation",
      "éthique",
    ],
    keywords: [
      "islam",
      "coran",
      "hadith",
      "jurisprudence",
      "musulman",
      "religieux",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Études Religieuses",
    slug: "etudes-religieuses",
    icon: "✝️",
    color: "#9C27B0",
    description:
      "Études des religions, christianisme, religions traditionnelles africaines.",
    longDescription:
      "Étude comparative des religions, christianisme, religions traditionnelles africaines, dialogue interreligieux, éthique religieuse et rôle des religions dans la société africaine.",
    examIds: [],
    series: ["Arts", "A", "L"],
    category: "sciences-sociales",
    subcategory: "études religieuses",
    isActive: true,
    difficulty: "facile",
    estimatedHours: 100,
    tags: [
      "religions",
      "christianisme",
      "traditions",
      "dialogue",
      "éthique",
      "spiritualité",
    ],
    keywords: [
      "religions",
      "christianisme",
      "traditions",
      "spiritualité",
      "foi",
      "croyances",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Santé et Nutrition",
    slug: "sante-et-nutrition",
    icon: "🏥",
    color: "#F44336",
    description:
      "Éducation à la santé, nutrition, hygiène, prévention des maladies.",
    longDescription:
      "Formation à l'éducation sanitaire, nutrition, hygiène, prévention des maladies tropicales, santé reproductive, santé communautaire et systèmes de santé en Afrique.",
    examIds: [],
    series: ["Science", "Technical", "Health"],
    category: "sciences",
    subcategory: "santé",
    isActive: true,
    difficulty: "facile",
    estimatedHours: 80,
    tags: [
      "santé",
      "nutrition",
      "hygiène",
      "prévention",
      "maladies",
      "communautaire",
    ],
    keywords: [
      "santé",
      "nutrition",
      "hygiène",
      "prévention",
      "médical",
      "bien-être",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Environnement et Développement Durable",
    slug: "environnement-et-developpement-durable",
    icon: "🌿",
    color: "#4CAF50",
    description:
      "Écologie, protection de l'environnement, développement durable.",
    longDescription:
      "Étude de l'environnement, écologie, changements climatiques, protection de la biodiversité, développement durable, énergies renouvelables et gestion des ressources naturelles africaines.",
    examIds: [],
    series: ["Science", "Arts", "Commercial"],
    category: "sciences",
    subcategory: "environnement",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 100,
    tags: [
      "environnement",
      "écologie",
      "durable",
      "climat",
      "biodiversité",
      "ressources",
    ],
    keywords: [
      "environnement",
      "écologie",
      "durable",
      "climat",
      "nature",
      "protection",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
  {
    name: "Entrepreneuriat",
    slug: "entrepreneuriat",
    icon: "💼",
    color: "#FF9800",
    description:
      "Création d'entreprise, gestion de projet, innovation, leadership.",
    longDescription:
      "Formation à l'entrepreneuriat, création et gestion d'entreprise, innovation, leadership, business plan, financement, marketing entrepreneurial adapté au contexte africain.",
    examIds: [],
    series: ["Commercial", "Technical", "E"],
    category: "sciences-sociales",
    subcategory: "entrepreneuriat",
    isActive: true,
    difficulty: "moyen",
    estimatedHours: 120,
    tags: [
      "entrepreneuriat",
      "entreprise",
      "innovation",
      "leadership",
      "business",
      "création",
    ],
    keywords: [
      "entrepreneuriat",
      "entreprise",
      "business",
      "innovation",
      "création",
      "gestion",
    ],
    popularity: 0,
    rating: { average: 0, count: 0 },
    statistics: {
      totalStudents: 0,
      totalExams: 0,
      averageScore: 0,
      completionRate: 0,
    },
  },
];

// Fonction pour ensemencer les matières
async function seedSubjects() {
  try {
    // Supprimer les matières existantes
    await Subject.deleteMany({});
    console.log("Matières existantes supprimées");

    // Insérer les nouvelles matières
    const insertedSubjects = await Subject.insertMany(subjects);
    console.log(`${insertedSubjects.length} matières créées avec succès`);

    // Afficher le résumé
    console.log("\n=== RÉSUMÉ DE L'ENSEMENCEMENT ===");
    console.log(`Total des matières créées : ${insertedSubjects.length}`);

    const categoryCounts = {};
    insertedSubjects.forEach((subject) => {
      categoryCounts[subject.category] =
        (categoryCounts[subject.category] || 0) + 1;
    });

    console.log("\nMatières par catégorie :");
    Object.entries(categoryCounts).forEach(([category, count]) => {
      console.log(`  ${category}: ${count} matières`);
    });

    const difficultyCounts = {};
    insertedSubjects.forEach((subject) => {
      difficultyCounts[subject.difficulty] =
        (difficultyCounts[subject.difficulty] || 0) + 1;
    });

    console.log("\nMatières par difficulté :");
    Object.entries(difficultyCounts).forEach(([difficulty, count]) => {
      console.log(`  ${difficulty}: ${count} matières`);
    });

    // Fermer la connexion
    await mongoose.connection.close();
    console.log("\nConnexion MongoDB fermée");
  } catch (err) {
    console.error("Erreur lors de l'ensemencement :", err);
    process.exit(1);
  }
}

// Exécuter la fonction d'ensemencement
seedSubjects();